---
# defaults file for roles/steam
steam_name: steam
steam_file: "https://client-update.steamstatic.com/installer/steamcmd_linux.tar.gz"
steam_user: "steam"
# Password login is locked until this value is overridden with a secure hash.
steam_user_pwd: "!"
steam_user_home: "/home/{{ steam_user }}"
steam_dir: "/opt/steam"
